### ISSUE TITLE
Autocrafting honey bottle to honey block does not return empty bottles.

### ISSUE THREAD

**Issue by karlheidar** [keksexception/AutoCraftNewMinecraft#1]
I have been trying this plugin, and it is very promising. 
The first issue is that Autocrafting honey bottle to honey block does not return empty bottles, as it should in regular crafting.

**Comment by keksexception** [comment]
Hello, thanks for your bugreport. Unfortunatly it is not possible to detect wether the bottles should be emptied or not (at the moment). I will try to find a solution for that, but i cant promise that it works.
