### ISSUE TITLE
TPS and Server lag on 1.19

### ISSUE THREAD

**Issue by karlheidar** [keksexception/AutoCraftNewMinecraft#2]
I experienced dramatic server lag after installing the plugin on my 1.19 server.
Please note the comments in plugin.yml where suggested changes are in API version from 1.14 to 1.19 :)

Karl

**Comment by keksexception** [comment]
Hey! thanks for your bugreport. I have not expercienced server impacts while testing the plugin on my 1.19 server, but i will run additional tests. There might be another plugin that interferes with autocraft. Please send me a list of your installed plugins (and if you are using normal spigot or paperspigot).
