### ISSUE TITLE
Deactivate Everything but the autocrafter

### ISSUE THREAD

**Issue by tzuzn** [keksexception/AutoCraftNewMinecraft#5]
Hi,
i wanted to just use the Autocrafter cause the Autoenchanter is to overpowered for my server.
Is there a way to deactivate all the other ones?

**Comment by keksexception** [comment]
Yes,
in your messages.yml you can disable the crafting recipes for the other blocks. Modify the following values:

 ALLOW_CRAFT_AUTOCRAFT=true;
ALLOW_CRAFT_AUTOENCHANT=false;
ALLOW_CRAFT_OREBLOCK=false;
ALLOW_CRAFT_BLOCKCRUSHER=false;

**Comment by tzuzn** [comment]
Ty for your help.
:)
