### ISSUE TITLE
Blocks broke

### ISSUE THREAD

**Issue by HungryHobos** [keksexception/AutoCraftNewMinecraft#6]
Broken when server restarted now cant place blacks in location was previously placed

**Comment by keksexception** [comment]
Hey! Thanks for the report!
Try the following steps:
1. Stop Server
2. Delete blockdata.json
3. Start Server again

Please let me know, if this worked and if there is any error displayed.

**Comment by HungryHobos** [comment]
I figured it out thanks tho honestly wasn't expecting a reply

**Comment by HungryHobos** [comment]
Idk man I just broke them and pushed the invisible block in to walls with a
piston lol
It would place blocks in the spot but they would be placed like the head on
top, like it was an item frame or something
hope that helps and make since

**Comment by keksexception** [comment]
Im glad that the problem is solved now!
For further questions and faster support i recommend my discord server:
https://discord.com/invite/zqByPVvxbr
