### ISSUE TITLE
Not Full nbt checking while using other plugins.

### ISSUE THREAD

**Issue by wondarkus** [keksexception/AutoCraftNewMinecraft#8]
Hello, I am using your awesome plugin on my server in conjunction with ValhallaMMO and ExecutableItems. Recipes I create through ValhallaMMO, including checking NBT tags when crafting. The plugin sees the recipe, but does not check the NBT tags of the item when crafting, which is why a person can deceive the system for crafting complex items and use an ordinary pyrotechnic star instead of an "Unstable Core" with a complex recipe. Can you fix this please? I will be glad for any answer!

**Comment by keksexception** [comment]
Hey! Thanks for your message. NBT-Tags are not handled by the recipes. They are seperatly set after crafting, so AutoCraft has no way to recieve information about the tags.

**Comment by wondarkus** [comment]
Can you please add NBT tag checking in the future?  The plugin works great, but that's pretty important for a plugin like this.  I would appreciate any answer, thanks in advance!

**Comment by keksexception** [comment]
I will try, but cannot promise that it will work.

**Comment by keksexception** [comment]
Unfortunately, I have to inform you that the feature you requested cannot be implemented, as the NBT checking is done by external plugins. This is a technical limitation that I cannot influence directly. 
Moreover, I want to inform you that I have no more time for the development of further features and plugins. I regret that I cannot give you a more positive message. The entire source code is available on GitHub and can be adapted by your server developer as desired. I thank you for your understanding and your support.
